name: test

on:
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore: 
      - '**.md'

jobs:
  test:
    runs-on:
      - macos-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Build
      run: |
        swift --version
        swift build
    - name: Test
      run: |
        swift test --enable-code-coverage
        
    - name: Convert code coverage
      run: |
        xcrun llvm-cov \
          export \
          --format=lcov \
          --instr-profile=.build/debug/codecov/default.profdata \
          .build/debug/unsafe-additionsPackageTests.xctest/Contents/MacOS/unsafe-additionsPackageTests \
          Sources \
          > \
          unsafe-additionsPackageTests.lcov
    - name: Upload code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash)